### PR TITLE
feat: Update to Firebase major Version 8

### PR DESCRIPTION
**Pull request by BrandonStalnaker**
# Summary

Update to most recent major version of Firebase Core

### CODE REVIEW

**Comment by BrandonStalnaker** [comment]
@rmi22186 This should probably also be done in the GA4 repository right?

**Comment by einsteinx2** [comment]
> @rmi22186 This should probably also be done in the GA4 repository right?

I actually just did that today :)

**Review by einsteinx2 — APPROVED** [review]
LGTM

**Comment by einsteinx2** [comment]
@BrandonStalnaker when you merge/release this, can you please comment on and close https://github.com/mparticle-integrations/mparticle-apple-integration-google-analytics-firebase/pull/13 linking to this PR?

**Review by rmi22186 — APPROVED** [review]

**Pull request merged**
